FROM golang:1.11-alpine3.7

RUN echo -e 'http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.7/main\nhttp://mirrors.tuna.tsinghua.edu.cn/alpine/v3.7/community' > /etc/apk/repositories

RUN apk add --no-cache \
    bash \
    mysql-client \
    gcc \
    jq \
    tzdata &&\
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime &&\
    echo "Asia/Shanghai" > /etc/timezone &&\
    rm -rf /var/cache/apk/*
