version: '2'
volumes:
  lets-encrypt:
    external: true
    driver: 'null'
services:
  # development
  lb:
    image: rancher/lb-service-haproxy:v0.7.1
    ports:
    - 443:443/tcp
    - 80:80/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: external=true
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'