concurrent = 3
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "gitlab-salix"
  url = "https://gitlab.chainnova.com/"
  token = "xbP4dixBBZhi9oYYy-dm"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "/ling2yt/ubuntu-awscli:16.04.3"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/ubuntu/.ssh:/ssh", "/builds:/builds:rw", "/usr/bin/docker:/bin/docker", "/var/run/docker.sock:/var/run/docker.sock", "/home/ubuntu/gitlab-runner/cache:/cache:rw"]
    pull_policy = "never"
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "antship-dashboard runner"
  url = "https://gitlab.chainnova.com/"
  token = "dcwMyHA1yWr1T4kmycfz"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "/ling2yt/ubuntu-awscli:16.04.3"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/ubuntu/.ssh:/ssh", "/builds:/builds:rw", "/usr/bin/docker:/bin/docker", "/var/run/docker.sock:/var/run/docker.sock", "/home/ubuntu/gitlab-runner/cache:/cache:rw"]
    pull_policy = "never"
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "antship-api runner"
  url = "https://gitlab.chainnova.com/"
  token = "m-txYGaH6RKEeJzmZ5ms"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "/ling2yt/ubuntu-awscli:16.04.3"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/ubuntu/.ssh:/ssh", "/builds:/builds:rw", "/usr/bin/docker:/bin/docker", "/var/run/docker.sock:/var/run/docker.sock", "/home/ubuntu/gitlab-runner/cache:/cache:rw"]
    pull_policy = "never"
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "antship-platform-fe runner"
  url = "https://gitlab.chainnova.com/"
  token = "dNzs2ffmymL9nDfkAByF"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "/ling2yt/ubuntu-awscli:16.04.3"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/ubuntu/.ssh:/ssh", "/builds:/builds:rw", "/usr/bin/docker:/bin/docker", "/var/run/docker.sock:/var/run/docker.sock", "/home/ubuntu/gitlab-runner/cache:/cache:rw"]
    pull_policy = "never"
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "salix tracing h5 runner"
  url = "https://gitlab.chainnova.com/"
  token = "MCrJh9UnisxUwhUsQ3E8"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "/ling2yt/ubuntu-awscli:16.04.3"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/ubuntu/.ssh:/ssh", "/builds:/builds:rw", "/usr/bin/docker:/bin/docker", "/var/run/docker.sock:/var/run/docker.sock", "/home/ubuntu/gitlab-runner/cache:/cache:rw"]
    pull_policy = "never"
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "xfreee runner fe"
  url = "https://gitlab.chainnova.com/"
  token = "SuazJNU3FNrTo62PBPPt"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "/ling2yt/ubuntu-awscli:16.04.3"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/ubuntu/.ssh:/ssh", "/builds:/builds:rw", "/usr/bin/docker:/bin/docker", "/var/run/docker.sock:/var/run/docker.sock", "/home/ubuntu/gitlab-runner/cache:/cache:rw"]
    pull_policy = "never"
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "fe-project group runner"
  url = "https://gitlab.chainnova.com/"
  token = "-S3_NCHA9yxmsGFwvajQ"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "/ling2yt/ubuntu-awscli:16.04.3"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/ubuntu/.ssh:/ssh", "/builds:/builds:rw", "/usr/bin/docker:/bin/docker", "/var/run/docker.sock:/var/run/docker.sock", "/home/ubuntu/gitlab-runner/cache:/cache:rw"]
    pull_policy = "never"
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "fe-project group runner"
  url = "https://gitlab.chainnova.com/"
  token = "Uqrr9gJa4Adwwwjbkvck"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "/ling2yt/ubuntu-awscli:16.04.3"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/ubuntu/.ssh:/ssh", "/builds:/builds:rw", "/usr/bin/docker:/bin/docker", "/var/run/docker.sock:/var/run/docker.sock", "/home/ubuntu/gitlab-runner/cache:/cache:rw"]
    pull_policy = "never"
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "salix-wrchain-runner"
  url = "https://gitlab.chainnova.com/"
  token = "L-HdcwRLt-BKEovJ--G7"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "/ling2yt/ubuntu-awscli:16.04.3"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/ubuntu/.ssh:/ssh", "/builds:/builds:rw", "/usr/bin/docker:/bin/docker", "/var/run/docker.sock:/var/run/docker.sock", "/home/ubuntu/gitlab-runner/cache:/cache:rw"]
    pull_policy = "never"
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "salix-wrchain-ci-runner"
  url = "https://gitlab.chainnova.com/"
  token = "p7Qxsze-Z9GnmQ6YrJCs"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "/ling2yt/ubuntu-awscli:16.04.3"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/ubuntu/.ssh:/ssh", "/builds:/builds:rw", "/usr/bin/docker:/bin/docker", "/var/run/docker.sock:/var/run/docker.sock", "/home/ubuntu/gitlab-runner/cache:/cache:rw"]
    pull_policy = "never"
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "NOVA STORIES GROUP RUNNER"
  url = "https://gitlab.chainnova.com/"
  token = "mjWLfz3isy4PLQHvs_Fa"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "/ling2yt/ubuntu-awscli:16.04.3"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/ubuntu/.ssh:/ssh", "/builds:/builds:rw", "/usr/bin/docker:/bin/docker", "/var/run/docker.sock:/var/run/docker.sock", "/home/ubuntu/gitlab-runner/cache:/cache:rw"]
    pull_policy = "never"
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "nebulae"
  url = "https://gitlab.chainnova.com/"
  token = "H1LQrAyTNkCWXd-qDyAV"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "/ling2yt/ubuntu-awscli:16.04.3"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/ubuntu/.ssh:/ssh", "/builds:/builds:rw", "/usr/bin/docker:/bin/docker", "/var/run/docker.sock:/var/run/docker.sock", "/home/ubuntu/gitlab-runner/cache:/cache:rw"]
    pull_policy = "never"
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "sinochem runner"
  url = "https://gitlab.chainnova.com/"
  token = "7Ei-mCPrVykgRShoBrv5"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "/ling2yt/ubuntu-awscli:16.04.3"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    volumes = ["/home/ubuntu/.ssh:/ssh", "/builds:/builds:rw", "/usr/bin/docker:/bin/docker", "/var/run/docker.sock:/var/run/docker.sock", "/home/ubuntu/gitlab-runner/cache:/cache:rw"]
    disable_cache = false
    pull_policy = "never"
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
