apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv031 
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 172.31.33.203
    path: /home/ubuntu/opt/nfs/sharedir/es 
