apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: flink-jobmanager
  namespace: flink
spec:
  serviceName: flink-jobmanager
  replicas: 1
  template:
    metadata:
      labels:
        app: flink-jobmanager
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - flink
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: flink-jobmanager
        imagePullPolicy: IfNotPresent
        image: flink
        resources:
          requests:
            memory: "1Gi"
            cpu: "300m"
        ports:
        - containerPort: 8081
          name: web
        - containerPort: 6123
          name: rpc
        env:
        - name : JOB_MANAGER_RPC_ADDRESS
          value: "flink-jobmanager.flink.svc.cluster.local"
        command:
        - sh
        - -c
        - /docker-entrypoint.sh jobmanager
#        readinessProbe:
#          exec:
#            command:
#            - "zkOk.sh"
#          initialDelaySeconds: 10
#          timeoutSeconds: 5
#        livenessProbe:
#          exec:
#            command:
#            - "zkOk.sh"
#          initialDelaySeconds: 10
#          timeoutSeconds: 5
        volumeMounts:
        - name: datadir
          mountPath: /flink/
        - name: flink-configmap
          mountPath: /opt/flink/conf/flink-conf.yaml
          subPath: flink-conf.yaml
#      securityContext:
#        runAsUser: 1000
#        fsGroup: 1000
      volumes:
<<<<<<< HEAD
      - name: datadir
        emptyDir: {}
      - name: flink-configmap
        configMap:
          name: flink-configmap
=======
      #- name: datadir
      #  emptyDir: {}
      - name: flink-configmap
        configMap:
          name: flink-configmap
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.beta.kubernetes.io/storage-class: "nfs"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
>>>>>>> d6a0df20c92a9177012385b8adf451ded50fa8f4

---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: flink
  labels:
    app: flink-jobmanager
spec:
  ports:
  - port: 8081
    name: web
  - port: 6123
    name: rpc
#  clusterIP: None
  selector:
    app: flink-jobmanager
